database:
  hostname: ***REMOVED***
  port: 32432
  dbname: ***REMOVED***
  user: ***REMOVED***
  password: ***REMOVED***

rabbitmq:
  hostname: ***REMOVED***
  port: 31052
  user: ***REMOVED***
  password: ***REMOVED***
  queue: roomdata

debug: false